version = 0.1

[default.deploy.parameters]
stack_name = "office-estudio-guiggi-backend"
resolve_s3 = true
s3_prefix = "office-estudio-guiggi-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev ProjectName=OfficeEstudioGuiggi"
image_repositories = []
